version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: impacta@123
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - impacta_rede

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    networks:
      - impacta_rede

networks:
  impacta_rede:
    driver: bridge

volumes:
  database:
  templates: